version: "3"

x-app: &app
  build:
    context: .
    target: wiki-base
  image: ghcr.io/scientist-softserv/playbook-v2:${TAG:-latest}
  volumes:
    - .:/app
  networks:
    internal:

volumes:
  db:

networks:
  local:

services:
  wiki:
    <<: *app
    env_file:
      - .env
    # NOTE: all common env variables moved to .env
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=wiki.test
    depends_on:
      db:
        condition: service_started
    networks:
      local:
    ports:
      - "3000:3000"

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      local: